### ISSUE TITLE
Add OptiNiSt to community tools list

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/nwb-overview#102]
OptiNiSt - Calcium Imaging Pipeline Tool

OptiNiSt(Optical Neuroimage Studio) helps researchers try multiple data analysis methods, visualize the results, and construct the data analysis pipelines easily and quickly. OptiNiSt’s data-saving format follows NWB standards.

It looks like it can read HDF5/NWB and outputs in NWB.

Documentation: https://optinist.readthedocs.io/en/latest/index.html
Code: https://github.com/oist/optinist/
Tutorial at CNS 2023: https://www.dropbox.com/sh/z0awh38hpwrjchs/AABjmXTvNjrHnsO9lh-jh9fma?dl=0

**Comment by bendichter** [comment]
wow, this is awesome!
