### ISSUE TITLE
Consider adding nwbview

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/nwb-overview#123]
**nwbview: Rust powered NWB viewer**

Code: https://github.com/brainhack-ch/nwbview
Requires HDF5 1.12 or earlier. Cannot be built with HDF5 1.14

It looks like an HDF5 viewer with some added features

Screenshot from their README
![image](https://github.com/NeurodataWithoutBorders/nwb-overview/assets/310197/f18325d4-ebd2-40e6-83dd-ab727a1dc997)

In development. It took a little effort to get this to work. My setup (I don't have rust installed globally) is:
```
conda create --name nwbview --yes
conda activate nwbview
mamba install "hdf5<1.14" rust --yes
HDF5_DIR="/Users/rly/mambaforge/envs/nwbview/" RUSTFLAGS="-C link-args=-Wl,-rpath,$HDF5_DIR/lib" cargo install nwbview
cd /Users/rly/.cargo/bin
./nwbview
```

**Comment by bendichter** [comment]
attn @anilbey

**Comment by anilbey** [comment]
Hello, it's good to see NWBView here :)

The hdf5 interface is via the [hdf5 Rust crate](https://crates.io/crates/hdf5). When the hdf5 crate makes a new release, it will most likely support the hdf5 version 1.14.

**Comment by anilbey** [comment]
The recent version of hdf5 seems to be supported by the hdf5-rust crate. It just hasn't released on Rust's package index yet.

Reference: https://github.com/aldanor/hdf5-rust/issues/262

**Comment by oruebel** [comment]
This issue has been resolved in https://github.com/NeurodataWithoutBorders/nwb-overview/pull/149
