### ISSUE TITLE
Add Allen Institute Brain Modeling Toolkit (BMTK) / SONATA 

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/nwb-overview#141]
https://github.com/AllenInstitute/bmtk

**Comment by oruebel** [comment]
Relevant resources:

- Documentation describing using NWB with BMTK: https://alleninstitute.github.io/bmtk/ecephys_probe.html
- Brief abstract describing the tools: https://www.braininitiative.org/toolmakers/resources/brain-modeling-tools-bmtk-sonata-vnd/
- Additional information: Tutorials on using BMTK https://alleninstitute.github.io/bmtk/tutorials.html

**Comment by oruebel** [comment]
I will make a PR for this. We should ask @kaeldai to review the PR once it's ready.
