### ISSUE TITLE
SpikeInterface listing not rendering correctly

### ISSUE THREAD

**Issue by oruebel** [NeurodataWithoutBorders/nwb-overview#22]
For some reason the list on the SpikeInterface tools page doesn't render correctly in ReadTheDocs. The image on the left shows how the page renders incorrectly in ReadTheDocs and on the right it shows how it renders (correctly) when I build the docs on my computer. The relevant file is [docs/source/tools/spikeinterface/spikeinterface.rst](https://github.com/NeurodataWithoutBorders/nwb-overview/blob/main/docs/source/tools/spikeinterface/spikeinterface.rst). Any idea what might be the problem?

<img width="1664" alt="Screen Shot 2022-03-13 at 6 46 01 PM" src="https://user-images.githubusercontent.com/10999845/158091019-1e911fd5-215e-494a-957e-aa6a942b94ba.png">

**Comment by bendichter** [comment]
I'm guessing it's a sphinx version issue

**Comment by bendichter** [comment]
I'll take a look
