### ISSUE TITLE
Review and add CICADA to nwb-overview

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/nwb-overview#68]
See reference in elife publication: https://elifesciences.org/articles/78116#s4-5-6
Documentation: https://pycicada.readthedocs.io/en/latest/tutorial.html
Source: https://gitlab.com/cossartlab/cicada/

**Comment by robin-dard** [comment]
One sentence description of cicada: "CICADA is a Python pipeline providing a graphical user interface (GUI) that allows the user to visualize, explore and analyze Calcium Imaging data contained in NWB files"
In addition to the link you have:
- Link to demo video: https://www.youtube.com/watch?v=xgf2RmrGVx0
- Link to the dandiset: https://dandiarchive.org/dandiset/000219?pos=1
Thanks
